Ci docker and jenkins fixes (#320)
* [refactor][docker] Permanently set jdk8u232b09 as JAVA_HOME in docker

* [refactor][docker] Use --no-check-certificate option with wget

* [refactor][docker] Resolved issue with CA certificates

* [refactor][jenkins] Updated slack channel and user home directory

* [refactor][jenkins] Remove visualization stage

* [refactor][jenkins] Removed unutilized webserver link

* [ci][refactor] Use mx testme to run Dacapo CI tests

* [ci][refactor] Use mx testme to run SPECjvm2008 CI tests

* [docker][fix] Install font libraries to resolve AWTFont crash

java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

* [ci][fix] Set jdk8U232 version in Jenkinsfile_bench

* [ci][feat] Add stage in Bench CI to check environment prerequisites

* [ci][feat] Enable artifact archiving for Benchmarking Jenkins Pipeline

* [ci][fix] Download and Install SPECjvm2008 in every build
This change ensures that env vars and/or permissions will be properly
set and will not affect benchmark's execution.

* [ci][fix] Set heap size to 16G for Ref & Max VM when run SPECjvm2008

* [ci][fix] Install SPECjvm2008 jar with JAVA_HOME

* [ci][refactor] Parallelize 'setup benchmark' stage

* [ci][fix] Enable assertions in Jenkins bench pipeline

* [ci][fix] Use AdoptOpenJDK8 u222 in Jenkins bench pipeline

* [ci][fix] Use AdoptOpenJDK8 u222 in Jenkins 'gate & cross-isa' pipeline

* [ci][refactor] Update mx version

* [ci][fix] Increase timeout to avoid ci build fails due to timeout

Co-authored-by: Thanos <tstratiko@gmail.com>